apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <head><title>NGINX Success</title></head>
      <body><h1>Hello from NGINX in EKS!</h1></body>
    </html>
